/* Generated By:JJTree&JavaCC: Do not edit this line. MicroblazeParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MicroblazeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADDRESS = 4;
  /** RegularExpression Id. */
  int INSTRUCTION_A1 = 5;
  /** RegularExpression Id. */
  int INSTRUCTION_A2 = 6;
  /** RegularExpression Id. */
  int INSTRUCTION_A3 = 7;
  /** RegularExpression Id. */
  int INSTRUCTION_B1 = 8;
  /** RegularExpression Id. */
  int INSTRUCTION_B2 = 9;
  /** RegularExpression Id. */
  int INSTRUCTION_B3 = 10;
  /** RegularExpression Id. */
  int REGISTER = 11;
  /** RegularExpression Id. */
  int LITERAL = 12;
  /** RegularExpression Id. */
  int LF = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\",\"",
    "\"\\r\"",
    "<ADDRESS>",
    "<INSTRUCTION_A1>",
    "<INSTRUCTION_A2>",
    "<INSTRUCTION_A3>",
    "<INSTRUCTION_B1>",
    "<INSTRUCTION_B2>",
    "<INSTRUCTION_B3>",
    "<REGISTER>",
    "<LITERAL>",
    "<LF>",
  };

}
