/* Generated By:JavaCC: Do not edit this line. MicroblazeParserTreeConstants.java Version 6.0_1 */
public interface MicroblazeParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTA1 = 2;
  public int JJTA2 = 3;
  public int JJTA3 = 4;
  public int JJTB1 = 5;
  public int JJTB2 = 6;
  public int JJTB3 = 7;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "A1",
    "A2",
    "A3",
    "B1",
    "B2",
    "B3",
  };
}
/* JavaCC - OriginalChecksum=98c47b2e62fd32c7390a02ff33e92a42 (do not edit this line) */
