/* MicroblazeParserTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. MicroblazeParserTokenManager.java */

/** Token Manager. */
@SuppressWarnings("unused")public class MicroblazeParserTokenManager implements MicroblazeParserConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 13:
         return jjStartNfaWithStates_0(0, 3, 11);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 490;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     { jjCheckNAdd(9); }
                  }
                  else if (curChar == 10)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 45)
                     { jjCheckNAdd(9); }
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) != 0L && kind > 11)
                     kind = 11;
                  break;
               case 5:
                  if ((0x6000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x3000000000000L & l) != 0L && kind > 11)
                     kind = 11;
                  break;
               case 8:
                  if (curChar == 45)
                     { jjCheckNAdd(9); }
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  { jjCheckNAdd(9); }
                  break;
               case 10:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
                  if (curChar == 10)
                     kind = 13;
                  break;
               case 63:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 71:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 76:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 82:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 211:
                  if (curChar == 32)
                     kind = 6;
                  break;
               case 327:
                  if (curChar == 56 && kind > 6)
                     kind = 6;
                  break;
               case 331:
                  if (curChar == 54 && kind > 6)
                     kind = 6;
                  break;
               case 332:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 336:
                  if (curChar == 50 && kind > 6)
                     kind = 6;
                  break;
               case 337:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 401:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 400;
                  break;
               case 407:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 406;
                  break;
               case 412:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 411;
                  break;
               case 417:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 416;
                  break;
               case 422:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 421;
                  break;
               case 427:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 426;
                  break;
               case 432:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 431;
                  break;
               case 456:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 455;
                  break;
               case 461:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 460;
                  break;
               case 466:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 465;
                  break;
               case 471:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 470;
                  break;
               case 476:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 475;
                  break;
               case 481:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 480;
                  break;
               case 486:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 485;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if (curChar == 100)
                     { jjAddStates(0, 13); }
                  else if (curChar == 102)
                     { jjAddStates(14, 27); }
                  else if (curChar == 99)
                     { jjAddStates(28, 31); }
                  else if (curChar == 105)
                     { jjAddStates(32, 35); }
                  else if (curChar == 115)
                     { jjCheckNAddStates(36, 57); }
                  else if (curChar == 108)
                     { jjCheckNAddStates(58, 73); }
                  else if (curChar == 98)
                     { jjAddStates(74, 117); }
                  else if (curChar == 114)
                     { jjAddStates(118, 129); }
                  else if (curChar == 97)
                     { jjAddStates(130, 141); }
                  else if (curChar == 109)
                     { jjAddStates(142, 149); }
                  else if (curChar == 120)
                     { jjAddStates(150, 151); }
                  else if (curChar == 111)
                     { jjCheckNAddTwoStates(86, 88); }
                  else if (curChar == 119)
                     { jjAddStates(152, 156); }
                  else if (curChar == 116)
                     { jjAddStates(157, 160); }
                  else if (curChar == 112)
                     { jjAddStates(161, 163); }
                  if (curChar == 114)
                     { jjAddStates(164, 166); }
                  break;
               case 0:
                  if (curChar == 120)
                     { jjCheckNAdd(1); }
                  break;
               case 1:
                  if ((0x7e00000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  { jjCheckNAdd(1); }
                  break;
               case 3:
                  if (curChar == 114)
                     { jjAddStates(164, 166); }
                  break;
               case 12:
                  if (curChar == 112)
                     { jjAddStates(161, 163); }
                  break;
               case 13:
                  if (curChar == 102 && kind > 7)
                     kind = 7;
                  break;
               case 14:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 113 && kind > 7)
                     kind = 7;
                  break;
               case 19:
               case 411:
               case 465:
                  if (curChar == 101)
                     { jjCheckNAdd(18); }
                  break;
               case 20:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 101 && kind > 7)
                     kind = 7;
                  break;
               case 24:
               case 426:
               case 480:
                  if (curChar == 110)
                     { jjCheckNAdd(23); }
                  break;
               case 25:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 116)
                     { jjAddStates(157, 160); }
                  break;
               case 29:
                  if (curChar == 100 && kind > 6)
                     kind = 6;
                  break;
               case 30:
               case 36:
               case 41:
               case 48:
               case 225:
               case 229:
                  if (curChar == 116)
                     { jjCheckNAdd(29); }
                  break;
               case 31:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 37:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 42:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 49:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 119)
                     { jjAddStates(152, 156); }
                  break;
               case 55:
                  if (curChar == 99 && kind > 6)
                     kind = 6;
                  break;
               case 56:
                  if (curChar == 105)
                     { jjCheckNAdd(55); }
                  break;
               case 57:
                  if (curChar == 100)
                     { jjCheckNAdd(55); }
                  break;
               case 58:
                  if (curChar == 104 && kind > 6)
                     kind = 6;
                  break;
               case 59:
                  if (curChar == 115)
                     { jjCheckNAdd(58); }
                  break;
               case 60:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 64:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 114 && kind > 6)
                     kind = 6;
                  break;
               case 67:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 72:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 97 && kind > 6)
                     kind = 6;
                  break;
               case 75:
                  if (curChar == 101)
                     { jjCheckNAdd(74); }
                  break;
               case 77:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 83:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 111)
                     { jjCheckNAddTwoStates(86, 88); }
                  break;
               case 86:
                  if (curChar == 114 && kind > 7)
                     kind = 7;
                  break;
               case 87:
                  if (curChar == 105 && kind > 10)
                     kind = 10;
                  break;
               case 88:
               case 91:
                  if (curChar == 114)
                     { jjCheckNAdd(87); }
                  break;
               case 89:
                  if (curChar == 120)
                     { jjAddStates(150, 151); }
                  break;
               case 90:
                  if (curChar == 111)
                     { jjCheckNAdd(86); }
                  break;
               case 92:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 109)
                     { jjAddStates(142, 149); }
                  break;
               case 94:
                  if (curChar == 108 && kind > 7)
                     kind = 7;
                  break;
               case 95:
               case 396:
               case 451:
                  if (curChar == 117)
                     { jjCheckNAdd(94); }
                  break;
               case 96:
                  if (curChar == 104 && kind > 7)
                     kind = 7;
                  break;
               case 97:
                  if (curChar == 108)
                     { jjCheckNAdd(96); }
                  break;
               case 98:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 117 && kind > 7)
                     kind = 7;
                  break;
               case 100:
               case 306:
                  if (curChar == 104)
                     { jjCheckNAdd(99); }
                  break;
               case 101:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 115)
                     { jjCheckNAdd(99); }
                  break;
               case 104:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 114 && kind > 8)
                     kind = 8;
                  break;
               case 108:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 114 && kind > 9)
                     kind = 9;
                  break;
               case 111:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 116 && kind > 9)
                     kind = 9;
                  break;
               case 116:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
               case 290:
               case 296:
               case 324:
               case 363:
                  if (curChar == 108)
                     { jjCheckNAdd(87); }
                  break;
               case 121:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 97)
                     { jjAddStates(130, 141); }
                  break;
               case 123:
                  if (curChar == 100 && kind > 7)
                     kind = 7;
                  break;
               case 124:
               case 391:
               case 446:
                  if (curChar == 100)
                     { jjCheckNAdd(123); }
                  break;
               case 125:
                  if (curChar == 99 && kind > 7)
                     kind = 7;
                  break;
               case 126:
                  if (curChar == 100)
                     { jjCheckNAdd(125); }
                  break;
               case 127:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 107 && kind > 7)
                     kind = 7;
                  break;
               case 129:
                  if (curChar == 100)
                     { jjCheckNAdd(128); }
                  break;
               case 130:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
               case 167:
                  if (curChar == 107)
                     { jjCheckNAdd(125); }
                  break;
               case 132:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 110)
                     { jjCheckNAdd(123); }
                  break;
               case 135:
                  if (curChar == 110 && kind > 7)
                     kind = 7;
                  break;
               case 136:
                  if (curChar == 100)
                     { jjCheckNAdd(135); }
                  break;
               case 137:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
               case 152:
                  if (curChar == 100)
                     { jjCheckNAdd(87); }
                  break;
               case 139:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 99 && kind > 10)
                     kind = 10;
                  break;
               case 141:
               case 183:
                  if (curChar == 105)
                     { jjCheckNAdd(140); }
                  break;
               case 142:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 107 && kind > 10)
                     kind = 10;
                  break;
               case 145:
               case 187:
                  if (curChar == 105)
                     { jjCheckNAdd(144); }
                  break;
               case 146:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
               case 191:
                  if (curChar == 107)
                     { jjCheckNAdd(140); }
                  break;
               case 149:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 153:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 110)
                     { jjCheckNAdd(87); }
                  break;
               case 155:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 114)
                     { jjAddStates(118, 129); }
                  break;
               case 158:
                  if (curChar == 98 && kind > 7)
                     kind = 7;
                  break;
               case 159:
               case 393:
               case 448:
                  if (curChar == 117)
                     { jjCheckNAdd(158); }
                  break;
               case 160:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 98)
                     { jjCheckNAdd(125); }
                  break;
               case 162:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 98)
                     { jjCheckNAdd(128); }
                  break;
               case 165:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 168:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 100 && kind > 9)
                     kind = 9;
                  break;
               case 172:
                  if (curChar == 115)
                     { jjCheckNAdd(171); }
                  break;
               case 173:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
               case 250:
               case 253:
               case 272:
               case 275:
               case 278:
               case 281:
               case 284:
               case 287:
                  if (curChar == 105)
                     { jjCheckNAdd(171); }
                  break;
               case 175:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 98)
                     { jjCheckNAdd(171); }
                  break;
               case 177:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 101)
                     { jjCheckNAdd(171); }
                  break;
               case 179:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
               case 360:
                  if (curChar == 98)
                     { jjCheckNAdd(87); }
                  break;
               case 181:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 184:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 188:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 192:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 98)
                     { jjAddStates(74, 117); }
                  break;
               case 197:
                  if (curChar == 114 && kind > 5)
                     kind = 5;
                  break;
               case 198:
                  if (curChar == 100 && kind > 5)
                     kind = 5;
                  break;
               case 199:
                  if (curChar == 114)
                     { jjCheckNAdd(198); }
                  break;
               case 200:
                  if (curChar == 97 && kind > 5)
                     kind = 5;
                  break;
               case 201:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 97)
                     { jjCheckNAdd(198); }
                  break;
               case 203:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
               case 206:
                  if (curChar == 108)
                     { jjCheckNAdd(29); }
                  break;
               case 205:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 207:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 107 && kind > 6)
                     kind = 6;
                  break;
               case 210:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 212:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 213:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 101 && kind > 6)
                     kind = 6;
                  break;
               case 215:
                  if (curChar == 110)
                     { jjCheckNAdd(214); }
                  break;
               case 216:
                  if (curChar == 116 && kind > 6)
                     kind = 6;
                  break;
               case 217:
               case 385:
                  if (curChar == 108)
                     { jjCheckNAdd(216); }
                  break;
               case 218:
                  if (curChar == 108)
                     { jjCheckNAdd(214); }
                  break;
               case 219:
                  if (curChar == 103)
                     { jjCheckNAdd(216); }
                  break;
               case 220:
                  if (curChar == 103)
                     { jjCheckNAdd(214); }
                  break;
               case 221:
                  if (curChar == 113)
                     { jjCheckNAdd(29); }
                  break;
               case 222:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
               case 227:
               case 231:
                  if (curChar == 101)
                     { jjCheckNAdd(29); }
                  break;
               case 224:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 226:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 228:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 230:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 232:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 114)
                     { jjCheckNAdd(94); }
                  break;
               case 234:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 97 && kind > 7)
                     kind = 7;
                  break;
               case 236:
                  if (curChar == 114)
                     { jjCheckNAdd(235); }
                  break;
               case 237:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 108)
                     { jjCheckNAdd(94); }
                  break;
               case 239:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 105 && kind > 8)
                     kind = 8;
                  break;
               case 241:
                  if (curChar == 114)
                     { jjCheckNAdd(240); }
                  break;
               case 242:
                  if (curChar == 100 && kind > 8)
                     kind = 8;
                  break;
               case 243:
               case 247:
                  if (curChar == 105)
                     { jjCheckNAdd(242); }
                  break;
               case 244:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 97)
                     { jjCheckNAdd(240); }
                  break;
               case 246:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 248:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 251:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 254:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 105 && kind > 9)
                     kind = 9;
                  break;
               case 258:
                  if (curChar == 107)
                     { jjCheckNAdd(257); }
                  break;
               case 259:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 113)
                     { jjCheckNAdd(257); }
                  break;
               case 261:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
               case 266:
               case 270:
                  if (curChar == 101)
                     { jjCheckNAdd(257); }
                  break;
               case 263:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
               case 268:
                  if (curChar == 116)
                     { jjCheckNAdd(257); }
                  break;
               case 265:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 267:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 269:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 271:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 273:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 274:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 276:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 279:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 280:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 282:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 285:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 288:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 289:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 291:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 293:
                  if (curChar == 97)
                     { jjCheckNAdd(87); }
                  break;
               case 294:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 295:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 297:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 298:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 299:
                  if (curChar == 108)
                     { jjCheckNAddStates(58, 73); }
                  break;
               case 300:
                  if (curChar == 98)
                     { jjCheckNAdd(99); }
                  break;
               case 301:
               case 307:
                  if (curChar == 117)
                     { jjCheckNAdd(86); }
                  break;
               case 302:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 303:
               case 309:
               case 316:
               case 350:
               case 353:
               case 357:
                  if (curChar == 101)
                     { jjCheckNAdd(235); }
                  break;
               case 304:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 308:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 310:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 311:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 312:
                  if (curChar == 119 && kind > 7)
                     kind = 7;
                  break;
               case 313:
               case 355:
                  if (curChar == 119)
                     { jjCheckNAdd(86); }
                  break;
               case 314:
                  if (curChar == 120 && kind > 7)
                     kind = 7;
                  break;
               case 315:
               case 356:
                  if (curChar == 119)
                     { jjCheckNAdd(314); }
                  break;
               case 317:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 318:
               case 359:
                  if (curChar == 108)
                     { jjCheckNAdd(86); }
                  break;
               case 319:
               case 321:
                  if (curChar == 117)
                     { jjCheckNAdd(87); }
                  break;
               case 320:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 322:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 323:
               case 362:
                  if (curChar == 119)
                     { jjCheckNAdd(87); }
                  break;
               case 325:
                  if (curChar == 115)
                     { jjCheckNAddStates(36, 57); }
                  break;
               case 326:
                  if (curChar == 114)
                     { jjCheckNAdd(74); }
                  break;
               case 328:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 327;
                  break;
               case 329:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 328;
                  break;
               case 330:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 333:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 334:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 333;
                  break;
               case 335:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 338:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 337;
                  break;
               case 339:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 340:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 339;
                  break;
               case 341:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 340;
                  break;
               case 342:
                  if (curChar == 98 && kind > 6)
                     kind = 6;
                  break;
               case 343:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 344:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 343;
                  break;
               case 345:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 344;
                  break;
               case 346:
                  if (curChar == 112)
                     { jjCheckNAdd(58); }
                  break;
               case 347:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 346;
                  break;
               case 348:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 349:
                  if (curChar == 98)
                     { jjCheckNAdd(86); }
                  break;
               case 351:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 350;
                  break;
               case 352:
                  if (curChar == 104)
                     { jjCheckNAdd(86); }
                  break;
               case 354:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 353;
                  break;
               case 358:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 357;
                  break;
               case 361:
                  if (curChar == 106)
                     { jjCheckNAdd(87); }
                  break;
               case 364:
                  if (curChar == 105)
                     { jjAddStates(32, 35); }
                  break;
               case 365:
                  if (curChar == 118 && kind > 7)
                     kind = 7;
                  break;
               case 366:
               case 398:
               case 453:
                  if (curChar == 105)
                     { jjCheckNAdd(365); }
                  break;
               case 367:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 366;
                  break;
               case 368:
                  if (curChar == 118)
                     { jjCheckNAdd(99); }
                  break;
               case 369:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 368;
                  break;
               case 370:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 369;
                  break;
               case 371:
                  if (curChar == 109 && kind > 8)
                     kind = 8;
                  break;
               case 372:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 371;
                  break;
               case 373:
                  if (curChar == 108 && kind > 8)
                     kind = 8;
                  break;
               case 374:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 373;
                  break;
               case 375:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 374;
                  break;
               case 376:
                  if (curChar == 99)
                     { jjAddStates(28, 31); }
                  break;
               case 377:
                  if (curChar == 122)
                     kind = 6;
                  break;
               case 378:
               case 379:
                  if (curChar == 108)
                     { jjCheckNAdd(377); }
                  break;
               case 380:
                  if (curChar == 112 && kind > 7)
                     kind = 7;
                  break;
               case 381:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 380;
                  break;
               case 382:
                  if (curChar == 112)
                     { jjCheckNAdd(99); }
                  break;
               case 383:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 382;
                  break;
               case 384:
                  if (curChar == 102)
                     { jjAddStates(14, 27); }
                  break;
               case 386:
                  if (curChar == 110)
                     { jjCheckNAdd(216); }
                  break;
               case 387:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 386;
                  break;
               case 388:
               case 443:
                  if (curChar == 114)
                     { jjCheckNAdd(216); }
                  break;
               case 389:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 388;
                  break;
               case 390:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 389;
                  break;
               case 392:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 391;
                  break;
               case 394:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 393;
                  break;
               case 395:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 394;
                  break;
               case 397:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 396;
                  break;
               case 399:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 398;
                  break;
               case 400:
               case 455:
                  if (curChar == 117)
                     { jjCheckNAdd(135); }
                  break;
               case 402:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 401;
                  break;
               case 403:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 402;
                  break;
               case 404:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 403;
                  break;
               case 405:
                  if (curChar == 116 && kind > 7)
                     kind = 7;
                  break;
               case 406:
               case 460:
                  if (curChar == 108)
                     { jjCheckNAdd(405); }
                  break;
               case 408:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 407;
                  break;
               case 409:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 408;
                  break;
               case 410:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 409;
                  break;
               case 413:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 412;
                  break;
               case 414:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 413;
                  break;
               case 415:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 414;
                  break;
               case 416:
               case 470:
                  if (curChar == 108)
                     { jjCheckNAdd(23); }
                  break;
               case 418:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 417;
                  break;
               case 419:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 418;
                  break;
               case 420:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 419;
                  break;
               case 421:
               case 475:
                  if (curChar == 103)
                     { jjCheckNAdd(405); }
                  break;
               case 423:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 422;
                  break;
               case 424:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 423;
                  break;
               case 425:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 424;
                  break;
               case 428:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 427;
                  break;
               case 429:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 428;
                  break;
               case 430:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 429;
                  break;
               case 431:
               case 485:
                  if (curChar == 103)
                     { jjCheckNAdd(23); }
                  break;
               case 433:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 432;
                  break;
               case 434:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 433;
                  break;
               case 435:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 434;
                  break;
               case 436:
                  if (curChar == 100)
                     { jjAddStates(0, 13); }
                  break;
               case 437:
                  if (curChar == 108 && kind > 6)
                     kind = 6;
                  break;
               case 438:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 437;
                  break;
               case 439:
                  if (curChar == 103 && kind > 6)
                     kind = 6;
                  break;
               case 440:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 439;
                  break;
               case 441:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 440;
                  break;
               case 442:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 441;
                  break;
               case 444:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 443;
                  break;
               case 445:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 444;
                  break;
               case 447:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 446;
                  break;
               case 449:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 448;
                  break;
               case 450:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 449;
                  break;
               case 452:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 451;
                  break;
               case 454:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 453;
                  break;
               case 457:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 456;
                  break;
               case 458:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 457;
                  break;
               case 459:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 458;
                  break;
               case 462:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 461;
                  break;
               case 463:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 462;
                  break;
               case 464:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 463;
                  break;
               case 467:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 466;
                  break;
               case 468:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 467;
                  break;
               case 469:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 468;
                  break;
               case 472:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 471;
                  break;
               case 473:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 472;
                  break;
               case 474:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 473;
                  break;
               case 477:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 476;
                  break;
               case 478:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 477;
                  break;
               case 479:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 478;
                  break;
               case 482:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 481;
                  break;
               case 483:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 482;
                  break;
               case 484:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 483;
                  break;
               case 487:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 486;
                  break;
               case 488:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 487;
                  break;
               case 489:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 488;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 490 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   438, 442, 445, 447, 450, 452, 454, 459, 464, 469, 474, 479, 484, 489, 385, 387, 
   390, 392, 395, 397, 399, 404, 410, 415, 420, 425, 430, 435, 378, 379, 381, 383, 
   367, 370, 372, 375, 326, 330, 335, 341, 345, 348, 158, 349, 351, 96, 352, 354, 
   312, 355, 356, 358, 94, 359, 360, 361, 362, 363, 300, 302, 305, 306, 308, 311, 
   312, 313, 315, 317, 94, 318, 320, 322, 323, 324, 197, 199, 201, 203, 205, 208, 
   210, 213, 215, 217, 218, 219, 220, 222, 224, 226, 228, 230, 232, 234, 237, 239, 
   241, 244, 246, 249, 252, 256, 259, 261, 263, 265, 267, 269, 271, 274, 277, 280, 
   283, 286, 289, 292, 295, 298, 160, 163, 166, 170, 173, 175, 177, 179, 182, 186, 
   190, 195, 124, 127, 130, 133, 134, 137, 139, 143, 147, 151, 153, 156, 95, 98, 
   102, 106, 109, 114, 119, 121, 90, 92, 56, 57, 65, 73, 84, 35, 40, 47, 
   53, 17, 22, 27, 4, 5, 6, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 44 && (0x100100000000L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public MicroblazeParserTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public MicroblazeParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 490; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  static public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ff1L, 
};
static final long[] jjtoSkip = {
   0xeL, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[490];
    static private final int[] jjstateSet = new int[2 * 490];

    
    static protected char curChar;
}
